name: oasis_uz_mobile
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  json_annotation: ^4.8.1
  build_runner: ^2.1.7
  http: ^1.1.0
  cached_network_image: ^3.2.3
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  dots_indicator: ^2.1.1
  shared_preferences: ^2.2.2
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.3
  table_calendar: ^3.0.9
  source_gen: ^1.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  google_sign_in: ^6.1.6
  image_picker: ^1.0.7
  multi_image_picker: ^4.8.01
  path_provider: ^2.1.3
  photo_view: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  flutter_launcher_icons: ^0.13.1

 
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/1024.png"

flutter:
  generate: true

  uses-material-design: true

  assets:
    # - lang/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
